config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  post 'bookings/new'

  get 'bookings/create'
  post 'bookings/create'

  root 'flights#index' 
  resources :flights

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  validates :code, presence: true, uniqueness: { case_sensitive: false },
                                   length:     { is: 3 }
  before_save :uppercase_code
  has_many :departing_flights, foreign_key: :from_airport_id, class_name: "Flight"
  has_many :arriving_flights,  foreign_key: :to_airport_id,   class_name: "Flight"

  def uppercase_code
    self.code.upcase!
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :tickets
  has_many :passengers, through: :tickets
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  validates :from_airport,   presence: true
  validates :to_airport,     presence: true
  validates :start_datetime, presence: true 
  validates :duration,       presence: true

  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport,   class_name: "Airport"
  has_many :bookings
  has_many :passengers,     through: :bookings

  def self.get_start_dates
    Flight.all.map{ |f| f.start_datetime.to_date }.uniq
  end

  def self.search(query)
    conditions = {}
    conditions[:from_airport_id] = query[:from_airport_id] unless query[:from_airport_id].blank?
    conditions[:to_airport_id]   = query[:to_airport_id]   unless query[:to_airport_id].blank?
    unless query[:start_datetime].blank?
      parsed_date = Date.parse(query[:start_datetime])
      conditions[:start_datetime]  = parsed_date.beginning_of_day..parsed_date.end_of_day
    end
    Flight.all.where(conditions)
  end
end

# Try the methods below, they can prove faster when implemented correctly


#   def self.search(attributes)
#     supported_filters = [:from_airport_id, :to_airport_id]
#     attributes.slice(*supported_filters).inject(self) do |scope, (key, value)|
#       value.present? ? scope.send(key, value) : scope
#     end  
#   end
# end

# def self.filter(attributes)
#     attributes.inject(self) do |scope, (key, value)|
#       return scope if value.blank?
#       case key.to_sym
#       when :id, :zip # direct search
#         scope.where(key => value)
#       when :city, :state # regexp search
#         scope.where(["#{key} ILIKE ?", "%#{value}%"])
#       when :order # order=field-(ASC|DESC)
#         attribute, order = value.split("-") 
#         scope.order("#{self.table_name}.#{attribute} #{order}")
#       else # unknown key (do nothing or raise error, as you prefer to)
#         scope
#       end 
#     end  
#   end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  validates :name,  presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tickets
  has_many :bookings, through: :tickets
  has_many :flights, through: :bookings
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :passenger
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :chosen_flight

  def chosen_flight
    Flight.find(session[:flight_id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new
    session[:flight_id] = @flight.id
    if params[:passengers_number]
      params[:passengers_number].to_i.times do
        @booking.passengers.build
      end
    else
      @booking.passengers.build
    end
  end

  # TODO: fix adding passengers to a booking if they exist in the db already

  def create
    @booking = chosen_flight.bookings.build(bookings_params)
    @booking[:flight_id] = session[:flight_id]
    if @booking.valid?
      @booking.save
      @booking.passengers.each do |p|
        Passenger.find_or_create_by(email: p[:email])
      # p.name = params[:passengers_attributes][:name]
        # passenger = Passenger.find_by(email: p[:email])
        # if !passenger && p.valid?
        #   p.save
        # else
        #   @booking.passengers << passenger
        # end
      end
    else
      flash.now[:failure] = "Something went wrong."
    end
    redirect_to root_url
  end

  private

    def bookings_params
      params.require(:booking).permit(:flight_id, :passengers_attributes => [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = Flight.search(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Book tickets</h1>
<%= form_for(@booking, url: { action: 'create' }) do |f| %>
  <P><b><%= "Flight #{chosen_flight.id} information:" %></b></P>
  <p><%= "From: #{Airport.find(chosen_flight.from_airport_id).code}" %></p>
  <p><%= "To: #{Airport.find(chosen_flight.to_airport_id).code}" %></p>
  <p><%= "On: #{@flight.start_datetime}" %></p>
  <p><%= "No. of tickets: #{params[:passengers_number]}" %></p>
  <%= f.fields_for :passengers do |passenger_form| %>
    <p>
      <%= passenger_form.label :name, "Full name:" %>
      <%= passenger_form.text_field :name %>
    </p>
    <p>
      <%= passenger_form.label :email, "Email:" %>
      <%= passenger_form.email_field :email %>
    </p>
  <% end %>
<%= f.submit "Book this flight" %>
<% end %>

app/views/flights/_flight_search_form.html.erb
<%= form_tag(flights_path, method: 'get') do |f| %> 
  <%= label_tag("Flight details: ") %>
  <p>
    <%= select_tag(:from_airport_id, options_for_select(Airport.all.map{ |a| [a.code, a.id]})) %> 
    <%= select_tag(:to_airport_id,   options_for_select(Airport.all.map{ |a| [a.code, a.id]})) %> 
    <%= select_tag(:start_datetime,  options_for_select(Flight.get_start_dates.sort), prompt: "Select date") %>
  </p>
  <p>
    <%= label_tag(:passengers_number, "No. of passengers: ") %>
    <%= select_tag(:passengers_number, options_for_select([1,2,3,4])) %>
  </p>
  <p>
    <%= submit_tag "Search" %>
  </p>
<% end %>

app/views/flights/_select_flight_form.html.erb
<%= form_tag(controller: 'bookings', action: 'new', method: 'get') %>
  <% @flights.each do |flight| %>
    <p>
      <%= radio_button_tag(:flight_id, "#{flight.id}")%>
      <%= label_tag(:flight, "#{Airport.find(flight.from_airport_id).code} to #{Airport.find(flight.to_airport_id).code}
                             leaving on #{flight.start_datetime}") %>
      <%= hidden_field_tag(:passengers_number, params[:passengers_number]) %>                             
    </p>
  <% end %>
  <p>
    <%= submit_tag "Book a flight" %>
  </p>

app/views/flights/index.html.erb
<h1>Find a flight</h1>
<%= render partial: 'flight_search_form' %>
<% unless @flights.empty? || (@flights.count == Flight.all.count) %>
  <%= render partial: 'select_flight_form' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>